### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by FloEdelmann** [FloEdelmann/fixture-converter#16]
A test suite would help finding errors in format import/export.

**Possible test case:** Given an _e:cue_ library.xml, test if consecutive import and export creates the same file again.

**Comment by fxedel** [comment]
I'd add a test directory with all the test data (fixtures, desired in- and output, etc.) and a testing script that checks if each test (convert X from Y into Z) fails or not.

(already working on it)

**Comment by fxedel** [comment]
Errors do not cause Travis CI to fail the test, e.g. see https://travis-ci.org/FloEdelmann/fixture-converter/jobs/161487875

**Comment by fxedel** [comment]
The test doesn't fail when the error is a problem with the implementation of the test (in this case, destructuring doesn't work) – I only let them fail when I definitely can say: The test works as expected, but it produces other results as desired.

Of course I can and will change to code to also make problems with the implementation fail the whole test.

**Comment by FloEdelmann** [comment]
But I don't just want to know if all the tests pass, but also if the main program fails in any other way than I expected. In this case, it's just destructuring that is not available until Node v5, but it may be some other problem I didn't think about.
