### ISSUE TITLE
Custom output file names

### ISSUE THREAD

**Issue by fxedel** [FloEdelmann/fixture-converter#27]
**Current situation**
- _ecue_: one file "UserLibrary.xml"
- _qlcplus_: multiple files (one per fixture) "manufacturer-name-fixture-name.qxf"
- _import_: one file "import_YYYY-MM-DD_HH-MM-SS.json"

**Enhancement**
It would be useful to specify what the output file is by some reasons:
- avoid overwriting existing output files, especially when exporting different sets of fixtures to ecue
- don't have to search for or guess the output file name without reading console output, especially the test script

**Implementation**
- Additional comman line option "-X filename" where X is a good character (not "o", it's already used)

**Problems**
- What to do with qlcplus, which has to create multiple files? Ignore the option? Force using a placeholder (e. g. "%FIXTURE%") when using qlcplus?

**Comment by FloEdelmann** [comment]
Why is `-o` already used?

It could also be useful to allow `%FIXTURE%` and `%MANUFACTURER%` placerholders in output directory and file names and specify both at once.
