### ISSUE TITLE
Test command line outputs

### ISSUE THREAD

**Issue by fxedel** [FloEdelmann/fixture-converter#28]
Check if `Handling %FORMAT% formatting...` (if exporting) and all `File "%OUTPUT%" successfully written.` are correctly printed.

**Comment by FloEdelmann** [comment]
Those things cannot be wrong and therefore also don't need testing.

**Comment by fxedel** [comment]
It's so little impact to implement this feature as I need to get the file name out of the console output for #25 anyway.
